################################################################
# Web configuration backend
################################################################
[web]
address = ":80"
################################################################
# Docker configuration backend
################################################################
[docker]
domain = "docker.local"
watch = true
Start Træfɪk:
