################################################################
# Web configuration backend
################################################################

# Enable web configuration backend
[web]

# Web administration port
#
# Required
#
address = ":8181"

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "projectx.nl"
watch = true
exposedbydefault = true
